
package com.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceHello", targetNamespace = "http://webservice.com/", wsdlLocation = "http://localhost:8091/CXFSpringServer/webservice/serviceHello?wsdl")
public class ServiceHello_Service
    extends Service
{

    private final static URL SERVICEHELLO_WSDL_LOCATION;
    private final static WebServiceException SERVICEHELLO_EXCEPTION;
    private final static QName SERVICEHELLO_QNAME = new QName("http://webservice.com/", "ServiceHello");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/CXFSpringServer/webservice/serviceHello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEHELLO_WSDL_LOCATION = url;
        SERVICEHELLO_EXCEPTION = e;
    }

    public ServiceHello_Service() {
        super(__getWsdlLocation(), SERVICEHELLO_QNAME);
    }

    public ServiceHello_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEHELLO_QNAME, features);
    }

    public ServiceHello_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICEHELLO_QNAME);
    }

    public ServiceHello_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEHELLO_QNAME, features);
    }

    public ServiceHello_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceHello_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceHello
     */
    @WebEndpoint(name = "ServiceHelloImplPort")
    public ServiceHello getServiceHelloImplPort() {
        return super.getPort(new QName("http://webservice.com/", "ServiceHelloImplPort"), ServiceHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHello
     */
    @WebEndpoint(name = "ServiceHelloImplPort")
    public ServiceHello getServiceHelloImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.com/", "ServiceHelloImplPort"), ServiceHello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEHELLO_EXCEPTION!= null) {
            throw SERVICEHELLO_EXCEPTION;
        }
        return SERVICEHELLO_WSDL_LOCATION;
    }

}
